use std::env;
use std::fs;
use std::path::Path;

fn main() {
    generate_calendar_data();
    generate_tithi_overrides();

    // Generate UniFFI scaffolding when feature is enabled
    #[cfg(feature = "uniffi-bindings")]
    {
        uniffi::generate_scaffolding("src/uniffi.udl")
            .expect("Failed to generate UniFFI scaffolding");
    }
}

fn generate_calendar_data() {
    println!("cargo:rerun-if-changed=data/bs_calendar_data.json");
    println!("cargo:rerun-if-changed=build.rs");

    let json_path = "data/bs_calendar_data.json";
    let json_content = match fs::read_to_string(json_path) {
        Ok(c) => c,
        Err(e) => {
            println!("cargo:error=Missing required file: {json_path} — {e}");
            println!("cargo:error=Run from the engine/ directory, or ensure data/bs_calendar_data.json exists.");
            std::process::exit(1);
        }
    };

    let data: serde_json::Value = match serde_json::from_str(&json_content) {
        Ok(d) => d,
        Err(e) => {
            println!("cargo:error=Failed to parse {json_path}: {e}");
            std::process::exit(1);
        }
    };

    let mut rust_code = String::new();
    rust_code.push_str("// Auto-generated from bs_calendar_data.json\n");
    rust_code.push_str("// DO NOT EDIT THIS FILE MANUALLY\n\n");
    rust_code.push_str("use chrono::NaiveDate;\n");
    rust_code.push_str("use crate::domain::bs_date::BsMonth;\n");
    rust_code.push_str("use crate::error::{BsCalendarError, Result};\n");
    rust_code.push_str("use crate::ports::CalendarProvider;\n\n");

    let version = match data["version"].as_str() {
        Some(v) => v,
        None => {
            println!("cargo:error={json_path}: missing or non-string 'version' field");
            std::process::exit(1);
        }
    };
    let description = match data["description"].as_str() {
        Some(d) => d,
        None => {
            println!("cargo:error={json_path}: missing or non-string 'description' field");
            std::process::exit(1);
        }
    };

    rust_code.push_str(&format!(
        "pub const CALENDAR_VERSION: &str = \"{}\";\n",
        version
    ));
    rust_code.push_str(&format!(
        "pub const CALENDAR_DESCRIPTION: &str = \"{}\";\n\n",
        description
    ));

    // Generate year data structures
    rust_code.push_str("#[derive(Debug, Clone, Copy)]\n");
    rust_code.push_str("pub struct YearData {\n");
    rust_code.push_str("    pub year: u16,\n");
    rust_code.push_str("    pub first_baisakh_year: i32,\n");
    rust_code.push_str("    pub first_baisakh_month: u32,\n");
    rust_code.push_str("    pub first_baisakh_day: u32,\n");
    rust_code.push_str("    pub days_in_months: [u8; 12],\n");
    rust_code.push_str("}\n\n");

    let years = match data["years"].as_array() {
        Some(y) => y,
        None => {
            println!("cargo:error={json_path}: missing or non-array 'years' field");
            std::process::exit(1);
        }
    };
    // The O(1) year lookup below indexes by (year - FIRST_YEAR), which
    // requires the years array to be contiguous and ascending. Verify at
    // build time so a data regression fails the build, not the lookup.
    let year_numbers: Vec<u64> = years
        .iter()
        .map(|y| y["year"].as_u64().expect("year field must be integer"))
        .collect();
    let first_year = *year_numbers.first().expect("years array must not be empty");
    for (i, &y) in year_numbers.iter().enumerate() {
        if y != first_year + i as u64 {
            println!("cargo:error={json_path}: years must be contiguous and ascending; found {y} at position {i} (expected {})", first_year + i as u64);
            std::process::exit(1);
        }
    }

    // Official status: prefer an explicit boolean in the data file; fall back
    // to an exact version-suffix convention. (A bare substring match on
    // "official" previously matched accidental occurrences.)
    let is_official = data["official"].as_bool().unwrap_or_else(|| {
        // Exact token at a name boundary ("official-..." / "...-official" /
        // "official"), never a bare substring (which would match
        // "unofficial").
        version == "official"
            || version.starts_with("official-")
            || version.ends_with("-official")
    });

    // Internal-consistency audit: each year's month lengths must sum to the
    // gap between its anchor and the next year's anchor. Known-bad years are
    // surfaced as build warnings (a data correction is required to fix them).
    {
        use chrono::NaiveDate;
        for w in years.windows(2) {
            let (a, b) = (&w[0], &w[1]);
            let anchor = |y: &serde_json::Value| {
                NaiveDate::from_ymd_opt(
                    y["first_baisakh"]["year"].as_i64().unwrap() as i32,
                    y["first_baisakh"]["month"].as_u64().unwrap() as u32,
                    y["first_baisakh"]["day"].as_u64().unwrap() as u32,
                )
                .unwrap()
            };
            let gap = (anchor(b) - anchor(a)).num_days();
            let total: i64 = a["days_in_months"]
                .as_array()
                .unwrap()
                .iter()
                .map(|d| d.as_i64().unwrap())
                .sum();
            if gap != total {
                println!(
                    "cargo:warning=bs_calendar_data.json: BS {} months sum to {total} days but anchor gap to the next year is {gap} — data needs correction",
                    a["year"]
                );
            }
        }
    }

    rust_code.push_str(&format!(
        "pub const CALENDAR_FIRST_YEAR: u16 = {first_year};\n"
    ));
    rust_code.push_str(&format!(
        "pub const CALENDAR_IS_OFFICIAL: bool = {is_official};\n\n"
    ));
    rust_code.push_str(&format!(
        "pub static CALENDAR_DATA: [YearData; {}] = [\n",
        years.len()
    ));

    for year_obj in years {
        let year = year_obj["year"].as_u64().expect("year field must be integer");
        let first_baisakh = &year_obj["first_baisakh"];
        let fb_year = first_baisakh["year"].as_i64().expect("first_baisakh.year must be integer");
        let fb_month = first_baisakh["month"].as_u64().expect("first_baisakh.month must be integer");
        let fb_day = first_baisakh["day"].as_u64().expect("first_baisakh.day must be integer");

        let days = year_obj["days_in_months"].as_array().expect("days_in_months must be array");
        let days_str: Vec<String> = days
            .iter()
            .map(|d| d.as_u64().expect("day count must be integer").to_string())
            .collect();

        rust_code.push_str("    YearData {\n");
        rust_code.push_str(&format!("        year: {},\n", year));
        rust_code.push_str(&format!("        first_baisakh_year: {},\n", fb_year));
        rust_code.push_str(&format!("        first_baisakh_month: {},\n", fb_month));
        rust_code.push_str(&format!("        first_baisakh_day: {},\n", fb_day));
        rust_code.push_str(&format!(
            "        days_in_months: [{}],\n",
            days_str.join(", ")
        ));
        rust_code.push_str("    },\n");
    }

    rust_code.push_str("];\n\n");

    // Generate the provider implementation
    rust_code.push_str("/// Static calendar data provider (zero-cost at runtime)\n");
    rust_code.push_str("#[derive(Debug, Clone, Copy)]\n");
    rust_code.push_str("pub struct StaticCalendarProvider {}\n\n");
    rust_code.push_str("impl StaticCalendarProvider {\n");
    rust_code.push_str("    pub const fn new() -> Self {\n");
    rust_code.push_str("        StaticCalendarProvider {}\n");
    rust_code.push_str("    }\n\n");
    rust_code.push_str("    fn get_year_data(&self, year: u16) -> Result<&'static YearData> {\n");
    rust_code.push_str("        // O(1): years are contiguous from CALENDAR_FIRST_YEAR (verified at build time)\n");
    rust_code.push_str("        year.checked_sub(CALENDAR_FIRST_YEAR)\n");
    rust_code.push_str("            .and_then(|idx| CALENDAR_DATA.get(idx as usize))\n");
    rust_code.push_str("            .ok_or(BsCalendarError::CalendarDataNotFound(year))\n");
    rust_code.push_str("    }\n");
    rust_code.push_str("}\n\n");

    rust_code.push_str("impl Default for StaticCalendarProvider {\n");
    rust_code.push_str("    fn default() -> Self {\n");
    rust_code.push_str("        Self::new()\n");
    rust_code.push_str("    }\n");
    rust_code.push_str("}\n\n");

    rust_code.push_str("impl CalendarProvider for StaticCalendarProvider {\n");
    rust_code.push_str("    fn get_month_days(&self, year: u16, month: BsMonth) -> Result<u8> {\n");
    rust_code.push_str("        let year_data = self.get_year_data(year)?;\n");
    rust_code.push_str("        let month_idx = month.to_u8() as usize - 1;\n");
    rust_code.push_str("        Ok(year_data.days_in_months[month_idx])\n");
    rust_code.push_str("    }\n\n");

    rust_code.push_str("    fn get_first_baisakh(&self, year: u16) -> Result<NaiveDate> {\n");
    rust_code.push_str("        let year_data = self.get_year_data(year)?;\n");
    rust_code.push_str("        NaiveDate::from_ymd_opt(\n");
    rust_code.push_str("            year_data.first_baisakh_year,\n");
    rust_code.push_str("            year_data.first_baisakh_month,\n");
    rust_code.push_str("            year_data.first_baisakh_day\n");
    rust_code.push_str("        ).ok_or_else(|| {\n");
    rust_code.push_str("            BsCalendarError::ConversionError(format!(\n");
    rust_code.push_str("                \"Invalid anchor date for BS year {}\", year\n");
    rust_code.push_str("            ))\n");
    rust_code.push_str("        })\n");
    rust_code.push_str("    }\n\n");

    rust_code.push_str("    fn get_year_months(&self, year: u16) -> Result<[u8; 12]> {\n");
    rust_code.push_str("        let year_data = self.get_year_data(year)?;\n");
    rust_code.push_str("        Ok(year_data.days_in_months)\n");
    rust_code.push_str("    }\n\n");

    rust_code.push_str("    fn has_year(&self, year: u16) -> bool {\n");
    rust_code.push_str("        year.checked_sub(CALENDAR_FIRST_YEAR)\n");
    rust_code.push_str("            .map(|idx| (idx as usize) < CALENDAR_DATA.len())\n");
    rust_code.push_str("            .unwrap_or(false)\n");
    rust_code.push_str("    }\n\n");

    rust_code.push_str("    fn version(&self) -> &str {\n");
    rust_code.push_str("        CALENDAR_VERSION\n");
    rust_code.push_str("    }\n\n");

    rust_code.push_str("    fn is_official(&self) -> bool {\n");
    rust_code.push_str("        CALENDAR_IS_OFFICIAL\n");
    rust_code.push_str("    }\n");
    rust_code.push_str("}\n");

    // Write the generated code
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("calendar_data.rs");
    fs::write(&dest_path, rust_code).expect("Failed to write generated calendar_data.rs");

    println!(
        "cargo:warning=Generated calendar data with {} years",
        years.len()
    );
}

fn generate_tithi_overrides() {
    use chrono::Datelike;
    println!("cargo:rerun-if-changed=data/tithi_exceptions.csv");
    let exceptions_path = "data/tithi_exceptions.csv";
    let mut overrides_code = String::new();
    overrides_code.push_str("// Auto-generated from tithi_exceptions.csv\n\n");

    let mut override_entries = Vec::new();

    if let Ok(content) = fs::read_to_string(exceptions_path) {
        let lines: Vec<&str> = content.lines().skip(1).collect(); // Skip header
        for line in lines {
            let parts: Vec<&str> = line.split(',').collect();
            if parts.len() >= 3 {
                let ad_date_str = parts[1];
                let tithi_name = parts[2];

                if tithi_name.is_empty() {
                    continue;
                }

                // Parse AD Date
                if let Ok(date) = chrono::NaiveDate::parse_from_str(ad_date_str, "%Y-%m-%d") {
                    // Map "Shukla Pratipada" -> "Tithi::ShuklaPratipada"
                    let variant = tithi_name.replace(" ", "");
                    override_entries.push(format!(
                        "    (({}, {}, {}), Tithi::{}),",
                        date.year(),
                        date.month(),
                        date.day(),
                        variant
                    ));
                }
            }
        }
    }

    overrides_code.push_str(&format!(
        "pub static TITHI_OVERRIDES: [((i32, u8, u8), Tithi); {}] = [\n",
        override_entries.len()
    ));
    for entry in &override_entries {
        overrides_code.push_str(entry);
        overrides_code.push('\n');
    }
    overrides_code.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path_overrides = Path::new(&out_dir).join("tithi_overrides_data.rs");
    fs::write(&dest_path_overrides, overrides_code)
        .expect("Failed to write generated tithi_overrides_data.rs");

    println!(
        "cargo:warning=Generated {} tithi overrides",
        override_entries.len()
    );
}
