#!/usr/bin/env bash
set -euo pipefail

echo "🍎 Building Universal macOS Binary & XCFramework..."

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 1. Install Dependencies
echo "📦 Ensuring Rust targets are installed..."
rustup target add x86_64-apple-darwin
rustup target add aarch64-apple-darwin

# 2. Build for both architectures
echo -e "${BLUE}🔨 Building for x86_64 (Intel)...${NC}"
cargo build --release \
    --target x86_64-apple-darwin \
    --features uniffi-bindings \
    --no-default-features \
    --manifest-path engine/Cargo.toml

echo -e "${BLUE}🔨 Building for aarch64 (Apple Silicon)...${NC}"
cargo build --release \
    --target aarch64-apple-darwin \
    --features uniffi-bindings \
    --no-default-features \
    --manifest-path engine/Cargo.toml

# 3. Create Universal Binary
echo -e "${BLUE}🔗 Creating universal binary...${NC}"
mkdir -p engine/target/universal-apple-darwin/release

lipo -create \
    engine/target/x86_64-apple-darwin/release/libbs_calendar_core.a \
    engine/target/aarch64-apple-darwin/release/libbs_calendar_core.a \
    -output engine/target/universal-apple-darwin/release/libbs_calendar_core.a

# 4. Generate Swift Bindings
echo -e "${BLUE}🔧 Generating Swift bindings...${NC}"
# Use local binary wrapper to avoid installation issues
cargo run --release --manifest-path engine/Cargo.toml \
    --features uniffi-bindings \
    --bin uniffi-bindgen \
    -- generate engine/src/uniffi.udl --language swift --out-dir dist/swift

# 5. Create XCFramework
echo -e "${BLUE}🏗️  Creating XCFramework...${NC}"
rm -rf dist/BsCalendarCore.xcframework
mkdir -p dist/BsCalendarCore.xcframework/macos-arm64_x86_64/Headers

# Copy universal library
cp engine/target/universal-apple-darwin/release/libbs_calendar_core.a \
   dist/BsCalendarCore.xcframework/macos-arm64_x86_64/

# Copy Swift bindings
cp dist/swift/bs_calendar_core.swift \
   dist/BsCalendarCore.xcframework/

# Copy module map if it exists
if [ -f "dist/swift/bs_calendar_coreFFI.modulemap" ]; then
    cp dist/swift/bs_calendar_coreFFI.modulemap \
       dist/BsCalendarCore.xcframework/macos-arm64_x86_64/module.modulemap
fi

# Copy C headers (generated by uniffi-bindgen)
if [ -f "dist/swift/bs_calendar_coreFFI.h" ]; then
    cp dist/swift/bs_calendar_coreFFI.h \
       dist/BsCalendarCore.xcframework/macos-arm64_x86_64/Headers/
fi

# Create Info.plist for XCFramework
cat > dist/BsCalendarCore.xcframework/Info.plist << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>AvailableLibraries</key>
    <array>
        <dict>
            <key>LibraryIdentifier</key>
            <string>macos-arm64_x86_64</string>
            <key>LibraryPath</key>
            <string>libbs_calendar_core.a</string>
            <key>SupportedArchitectures</key>
            <array>
                <string>arm64</string>
                <string>x86_64</string>
            </array>
            <key>SupportedPlatform</key>
            <string>macos</string>
        </dict>
    </array>
    <key>CFBundlePackageType</key>
    <string>XFWK</string>
    <key>XCFrameworkFormatVersion</key>
    <string>1.0</string>
</dict>
</plist>
EOF

echo -e "${GREEN}✅ Build Complete!${NC}"
echo -e "XCFramework: ${BLUE}dist/BsCalendarCore.xcframework${NC}"
echo -e "Swift Bindings: ${BLUE}dist/swift/bs_calendar_core.swift${NC}"
